frr defaults datacenter
!
!
interface Ethernet1-1
  ip address 10.0.23.0/31
!
interface Ethernet1-2
  ip address 10.0.24.0/31
!
interface Ethernet1-3
  ip address 192.168.2.1/24
!
!
router bgp 2
  bgp bestpath as-path multipath-relax
  neighbor 10.0.23.1 remote-as 3
  neighbor 10.0.24.1 remote-as 4
  network 192.168.2.0/24
